/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'CLI',
      items: ['cli/reference'],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        'sdk/client-methods',
        {
          type: 'autogenerated',
          dirName: 'sdk/reference',
        },
      ],
    },
  ],
};

module.exports = sidebars;
