export const erc20HolderRewardsAbi = [
  {
    type: 'error',
    name: 'HolderRewardsAlreadyInitialized',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HolderRewardsInvalidRewardToken',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HolderRewardsInvalidRecipient',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HolderRewardsReentrantCall',
    inputs: [],
  },
  {
    type: 'error',
    name: 'HolderRewardsSystemExcluded',
    inputs: [{ name: 'account', type: 'address' }],
  },
  {
    type: 'error',
    name: 'HolderRewardsZeroAmountReceived',
    inputs: [],
  },
  {
    type: 'function',
    name: 'rewardToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'accRewardPerEligibleToken',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'eligibleSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingUndistributedRewards',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'accountedRewardBalance',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalHolderRewardsAccrued',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalHolderRewardsClaimed',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'rewardsExcluded',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'systemRewardsExcluded',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ownerRewardsExcluded',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'rewardCorrections',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'int256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimedRewards',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'claimableRewards',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'notifyHolderRewards',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'syncRewards',
    inputs: [],
    outputs: [{ name: 'synced', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimRewards',
    inputs: [{ name: 'recipient', type: 'address' }],
    outputs: [{ name: 'claimed', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addRewardsExcluded',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeRewardsExcluded',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'HolderRewardsNotified',
    inputs: [
      { name: 'funder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'HolderRewardsSynced',
    inputs: [{ name: 'amount', type: 'uint256', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'HolderRewardsClaimed',
    inputs: [
      { name: 'account', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RewardsExcluded',
    inputs: [{ name: 'account', type: 'address', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RewardsIncluded',
    inputs: [{ name: 'account', type: 'address', indexed: true }],
    anonymous: false,
  },
] as const;
