export const liquidFactoryAbi = [
  {
    type: 'error',
    name: 'AddressZero',
    inputs: [],
  },
  {
    type: 'error',
    name: 'EnforcedPause',
    inputs: [],
  },
  {
    type: 'error',
    name: 'ImplementationNotSet',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTokenKind',
    inputs: [{ name: 'kind', type: 'bytes32' }],
  },
  {
    type: 'error',
    name: 'InvalidAmount',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidName',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidPoolHook',
    inputs: [{ name: 'poolHooks', type: 'address' }],
  },
  {
    type: 'error',
    name: 'InvalidSymbol',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTickRange',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTickSpacing',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidTokenURI',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PoolHookMissingFlags',
    inputs: [
      { name: 'poolHooks', type: 'address' },
      { name: 'actualFlags', type: 'uint160' },
      { name: 'requiredFlags', type: 'uint160' },
    ],
  },
  {
    type: 'error',
    name: 'PoolHookNotGuard',
    inputs: [{ name: 'poolHooks', type: 'address' }],
  },
  {
    type: 'error',
    name: 'PoolHooksNotSet',
    inputs: [],
  },
  {
    type: 'error',
    name: 'PoolHookRareTokenMismatch',
    inputs: [
      { name: 'poolHooks', type: 'address' },
      { name: 'hookRareToken', type: 'address' },
      { name: 'expectedRareToken', type: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'SovereignRewardTokenNotAllowed',
    inputs: [{ name: 'rewardToken', type: 'address' }],
  },
  {
    type: 'error',
    name: 'TokenImplementationDisabled',
    inputs: [{ name: 'kind', type: 'bytes32' }],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address' }],
  },
  {
    type: 'error',
    name: 'SwapGuardFactoryMismatch',
    inputs: [
      { name: 'poolHooks', type: 'address' },
      { name: 'configuredFactory', type: 'address' },
      { name: 'expectedFactory', type: 'address' },
    ],
  },
  {
    type: 'error',
    name: 'Unauthorized',
    inputs: [],
  },
  {
    type: 'function',
    name: 'liquidMultiCurveImplementation',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'baseToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolManager',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'maxTotalSupply',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'creatorLaunchReward',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'minRareLiquidityWei',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpTickLower',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lpTickUpper',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolTickSpacing',
    inputs: [],
    outputs: [{ name: '', type: 'int24' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'poolHooks',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'SELF_REWARD_TOKEN',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'KIND_SOVEREIGN_ERC20',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'KIND_SOVEREIGN_ERC20_MARKET',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'KIND_SOVEREIGN_ERC20_MARKET_REWARDS',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'tokenImplementations',
    inputs: [{ name: 'kind', type: 'bytes32' }],
    outputs: [
      { name: 'implementation', type: 'address' },
      { name: 'enabled', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'sovereignRewardTokenAllowed',
    inputs: [{ name: 'rewardToken', type: 'address' }],
    outputs: [{ name: 'allowed', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isSovereignRewardTokenAllowed',
    inputs: [{ name: 'rewardToken', type: 'address' }],
    outputs: [{ name: 'allowed', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isCreatorDelegate',
    inputs: [
      { name: 'creator', type: 'address' },
      { name: 'operator', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'delegateTokenCreation',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revokeTokenCreationDelegate',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLiquidTokenMultiCurve',
    inputs: [
      { name: '_creator', type: 'address' },
      { name: '_tokenUri', type: 'string' },
      { name: '_name', type: 'string' },
      { name: '_symbol', type: 'string' },
      { name: '_initialRareLiquidity', type: 'uint256' },
      {
        name: '_curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createLiquidTokenMultiCurveWithSupply',
    inputs: [
      { name: '_creator', type: 'address' },
      { name: '_tokenUri', type: 'string' },
      { name: '_name', type: 'string' },
      { name: '_symbol', type: 'string' },
      { name: '_initialRareLiquidity', type: 'uint256' },
      {
        name: '_curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
      { name: '_customMaxTotalSupply', type: 'uint256' },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSovereignERC20',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'tokenUri', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'initialSupply', type: 'uint256' },
      { name: 'maxSupply', type: 'uint256' },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSovereignERC20Market',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'tokenUri', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'initialSupply', type: 'uint256' },
      {
        name: 'curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSovereignERC20MarketRewards',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'tokenUri', type: 'string' },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'initialSupply', type: 'uint256' },
      {
        name: 'curves',
        type: 'tuple[]',
        components: [
          { name: 'tickLower', type: 'int24' },
          { name: 'tickUpper', type: 'int24' },
          { name: 'numPositions', type: 'uint16' },
          { name: 'shares', type: 'uint256' },
        ],
      },
      { name: 'rewardToken', type: 'address' },
    ],
    outputs: [{ name: 'token', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'LiquidTokenCreated',
    inputs: [
      { name: 'token', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'tokenUri', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CreatorDelegateUpdated',
    inputs: [
      { name: 'creator', type: 'address', indexed: true },
      { name: 'operator', type: 'address', indexed: true },
      { name: 'approved', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SovereignTokenCreated',
    inputs: [
      { name: 'kind', type: 'bytes32', indexed: true },
      { name: 'token', type: 'address', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'tokenUri', type: 'string', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SovereignTokenImplementationUpdated',
    inputs: [
      { name: 'kind', type: 'bytes32', indexed: true },
      { name: 'oldImplementation', type: 'address', indexed: true },
      { name: 'newImplementation', type: 'address', indexed: true },
      { name: 'enabled', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SovereignRewardTokenAllowlistUpdated',
    inputs: [
      { name: 'rewardToken', type: 'address', indexed: true },
      { name: 'allowed', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
] as const;
