/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/nfts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List NFTs
         * @description Search, filter, and list NFTs with rich query parameters
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    /** @description Full-text search */
                    q?: string;
                    /** @description Checksummed Ethereum address */
                    creatorAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Checksummed Ethereum address */
                    ownerAddress?: components["schemas"]["EthereumAddress"];
                    /** @description Checksummed Ethereum address */
                    contractAddress?: components["schemas"]["EthereumAddress"] & unknown;
                    collectionId?: string;
                    /** @description Supported blockchain network id */
                    chainId?: components["schemas"]["ChainId"];
                    hasAuction?: boolean | null;
                    auctionState?: "PENDING" | "RUNNING" | "UNSETTLED";
                    auctionType?: "RESERVE_AUCTION" | "BATCH_RESERVE_AUCTION" | "SCHEDULED_AUCTION";
                    hasListing?: boolean | null;
                    hasOffer?: boolean | null;
                    isPrimarySale?: boolean | null;
                    isSecondarySale?: boolean | null;
                    priceMin?: number | null;
                    priceMax?: number | null;
                    /** @description Checksummed Ethereum address */
                    currency?: components["schemas"]["EthereumAddress"] & unknown;
                    mediaType?: "IMAGE" | "VIDEO" | "GIF" | "3D" | "HTML" | "AUDIO";
                    tags?: string[] | string;
                    sortBy?: "newest" | "oldest" | "priceAsc" | "priceDesc" | "recentlySold" | "auctionEndingSoon" | "recentActivity" | "bidAsc" | "bidDesc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of NFTs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Nft"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/{universalTokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get NFT
         * @description Get a single NFT by its universal token ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Canonical NFT identifier in chainId-contractAddress-tokenId format. */
                    universalTokenId: components["schemas"]["UniversalTokenId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description NFT detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Nft"];
                        };
                    };
                };
                /** @description NFT not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/{universalTokenId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List NFT events
         * @description Get events for a specific NFT
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    eventType?: ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY")[] | ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY");
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path: {
                    /** @description Canonical NFT identifier in chainId-contractAddress-tokenId format. */
                    universalTokenId: components["schemas"]["UniversalTokenId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of NFT events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NftEvent"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pin NFT Metadata
         * @description Assemble NFT metadata JSON from media assets and pin to IPFS via Filebase
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateNftMetadataRequest"];
                };
            };
            responses: {
                /** @description Metadata pinned to IPFS */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateNftMetadataResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Media Upload
         * @description Initiate a multipart upload to Filebase/IPFS, returning presigned URLs for each part
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateMediaUploadRequest"];
                };
            };
            responses: {
                /** @description Multipart upload initiated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateMediaUploadResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Media Upload
         * @description Complete a multipart upload, resolve IPFS CID, and return IPFS/gateway URLs
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteMediaUploadRequest"];
                };
            };
            responses: {
                /** @description Upload completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IpfsUploadResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/nfts/metadata/media/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Media Metadata
         * @description Call pipelines to extract media metadata (dimensions, size, type) from a URI
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GenerateMediaRequest"];
                };
            };
            responses: {
                /** @description Media metadata generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenerateMediaResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collections
         * @description Search, filter, and list collections
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    /** @description Full-text search */
                    q?: string;
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collections */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Collection"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get collection
         * @description Get a single collection by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Collection detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Collection"];
                        };
                    };
                };
                /** @description Collection not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List collection events
         * @description Get events across all NFTs in a collection
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    perPage?: number;
                    eventType?: ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY")[] | ("CANCEL_AUCTION" | "CANCEL_OFFER" | "CLOSE_AUCTION" | "CREATE_NFT" | "CREATE_NFT_SUPPLY" | "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "END_AUCTION" | "MAKE_AUCTION_BID" | "MAKE_LISTING" | "MAKE_OFFER" | "SETTLE_AUCTION" | "START_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER" | "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY");
                    sortBy?: "newest" | "oldest";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of collection events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["NftEvent"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/collections/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import ERC-721 Collection
         * @description Validate an ERC-721 contract on-chain and register it for indexing via pipelines
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ImportCollectionRequest"];
                };
            };
            responses: {
                /** @description Collection imported or already exists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportCollectionResponse"];
                    };
                };
                /** @description Validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
                /** @description Collection already indexed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            collectionId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{address}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Get a user profile by Ethereum address
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Checksummed Ethereum address */
                    address: components["schemas"]["EthereumAddress"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User profile */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserProfile"];
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tokens/price/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Price
         * @description Fetch the current USD price for a token by symbol (e.g., rare, eth, usdc)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Token symbol (case-insensitive) */
                    symbol: components["schemas"]["TokenSymbol"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token price */
                200: {
                    headers: {
                        "Cache-Control": string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPriceResponse"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Nft: {
            /** @example 1-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-12345 */
            universalTokenId: string;
            /** @example 0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0 */
            contractAddress: string;
            /** @example 1 */
            chainId: string;
            /** @example 12345 */
            tokenId: string;
            /**
             * @example ERC721
             * @enum {string}
             */
            type: "ERC721" | "ERC1155";
            creator: components["schemas"]["User"];
            owner: components["schemas"]["User"];
            owners?: {
                /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
                address: string;
                /** @example 1 */
                balance: string;
            }[];
            metadata: {
                /** @example Genesis */
                name: string | null;
                /** @example A unique digital artwork */
                description: string | null;
                /**
                 * @example [
                 *       "art",
                 *       "digital"
                 *     ]
                 */
                tags: string[];
                /** @example image/png */
                mediaType: string | null;
                /** @example https://example.com/image.png */
                imageUri: string | null;
                /** @example null */
                videoUri: string | null;
            };
            market: {
                listings: components["schemas"]["Listing"][];
                offers: components["schemas"]["Offer"][];
                auctions: components["schemas"]["Auction"][];
            };
            lastSale: components["schemas"]["LastSale"];
            attributes: {
                /** @example Background */
                property: string;
                /** @example Blue */
                value: string;
            }[];
            /** @example 1704067200 */
            createdAt: number;
        };
        User: {
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            address: string;
            /** @example satoshi */
            username: string | null;
            /** @example https://example.com/avatar.png */
            avatar: string | null;
            /** @example Satoshi Nakamoto */
            fullName: string | null;
        };
        Listing: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example SALE_PRICE
             * @enum {string}
             */
            type: "SALE_PRICE" | "BATCH_SALE_PRICE";
            price: components["schemas"]["CryptoValue"];
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            seller: string;
        };
        CryptoValue: {
            /** @example 1000000000000000000 */
            cryptoAmount: string;
            currency: components["schemas"]["Currency"];
            /** @example 3500 */
            usdAmount: number | null;
        };
        Currency: {
            /** @example 0x0000000000000000000000000000000000000000 */
            address: string;
            /** @example ETH */
            symbol: string;
            /** @example 18 */
            decimals: number;
            /** @example 1 */
            chainId: number;
        };
        Offer: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example OFFER
             * @enum {string}
             */
            type: "OFFER" | "BATCH_OFFER";
            price: components["schemas"]["CryptoValue"];
            buyer: components["schemas"]["User"] & unknown;
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            buyerAddress: string;
        };
        Auction: {
            /** @example 0x1234567890abcdef1234567890abcdef12345678 */
            contractAddress: string;
            /**
             * @example RESERVE_AUCTION
             * @enum {string}
             */
            type: "RESERVE_AUCTION" | "BATCH_RESERVE_AUCTION" | "SCHEDULED_AUCTION";
            /**
             * @example RUNNING
             * @enum {string}
             */
            state: "PENDING" | "RUNNING" | "SETTLED" | "UNSETTLED";
            /** @example 2024-01-01T00:00:00.000Z */
            startTime: string | null;
            /** @example 2024-01-02T00:00:00.000Z */
            endTime: string | null;
            /** @example 0x0000000000000000000000000000000000000000 */
            currencyAddress: string;
            currentBid: components["schemas"]["CryptoValue"] & unknown;
            reservePrice: components["schemas"]["CryptoValue"] & unknown;
            highestBidder: components["schemas"]["User"] & unknown;
        };
        LastSale: {
            /** @example evt_123 */
            eventId: string;
            price: components["schemas"]["CryptoValue"];
        } | null;
        Pagination: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            perPage: number;
            /** @example 100 */
            totalCount: number;
            /** @example 5 */
            totalPages: number;
        };
        /**
         * @description Checksummed Ethereum address
         * @example 0xba5BDe662c17e2aDFF1075610382B9B691296350
         */
        EthereumAddress: string;
        /**
         * @description Supported blockchain network id
         * @example 1
         */
        ChainId: number;
        /**
         * @description Canonical NFT identifier in chainId-contractAddress-tokenId format.
         * @example 1-0xb932a70a57673d89f4acffbe830e8ed7f75fb9e0-12345
         */
        UniversalTokenId: string;
        NftEvent: components["schemas"]["SaleEvent"] | components["schemas"]["TransferEvent"] | components["schemas"]["CreationEvent"] | components["schemas"]["ListingEvent"] | components["schemas"]["OfferEvent"] | components["schemas"]["AuctionBidEvent"] | components["schemas"]["AuctionLifecycleEvent"];
        SaleEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "SETTLE_AUCTION" | "TAKE_LISTING" | "TAKE_OFFER";
            buyer: components["schemas"]["User"];
            seller: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
        };
        TransferEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "TRANSFER_NFT" | "TRANSFER_NFT_SUPPLY";
            from: components["schemas"]["User"];
            to: components["schemas"]["User"];
            /** @example 1 */
            amount?: string;
        };
        CreationEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "CREATE_NFT" | "CREATE_NFT_SUPPLY";
            creator: components["schemas"]["User"];
            /** @example 100 */
            amount?: string;
        };
        ListingEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_LISTING";
            price: components["schemas"]["CryptoValue"];
            targetBuyer: components["schemas"]["User"] & unknown;
        };
        OfferEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_OFFER" | "CANCEL_OFFER";
            buyer: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
        };
        AuctionBidEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "MAKE_AUCTION_BID";
            bidder: components["schemas"]["User"];
            price: components["schemas"]["CryptoValue"];
            previousBidder: components["schemas"]["User"] & unknown;
            /** @example false */
            extendsAuction: boolean;
        };
        AuctionLifecycleEvent: {
            /** @example evt_123 */
            eventId: string;
            /** @example 2024-01-01T00:00:00.000Z */
            createdAt: string;
            /** @example 0xabc123 */
            transactionHash: string | null;
            /** @example 12345678 */
            blockNumber: number | null;
            /** @enum {string} */
            eventType: "CREATE_RESERVE_AUCTION" | "CREATE_SCHEDULED_AUCTION" | "START_AUCTION" | "END_AUCTION" | "CANCEL_AUCTION" | "CLOSE_AUCTION";
            seller: components["schemas"]["User"] & unknown;
            buyer: components["schemas"]["User"] & unknown;
            price: components["schemas"]["CryptoValue"] & unknown;
            minimumBid: components["schemas"]["CryptoValue"] & unknown;
            /** @example 2024-01-01T00:00:00.000Z */
            startTime: string | null;
        };
        CreateNftMetadataResponse: {
            cid: string;
            ipfsUrl: string;
            gatewayUrl: string;
            metadata: {
                name: string;
                description: string;
                image: string;
                media: {
                    uri: string;
                    mimeType: string;
                    size?: number;
                    dimensions?: string;
                };
                animation_url?: string;
                tags: string[];
                attributes?: {
                    trait_type: string;
                    value: string | number | boolean;
                    display_type?: string;
                }[];
            };
        };
        CreateNftMetadataRequest: {
            /** @example My NFT */
            name: string;
            /** @example A beautiful artwork */
            description: string;
            /**
             * @example [
             *       "art",
             *       "digital"
             *     ]
             */
            tags: string[];
            attributes?: {
                trait_type: string;
                value: string | number | boolean;
                display_type?: string;
            }[];
            nftMedia: components["schemas"]["NftMediaInput"];
        };
        NftMediaInput: {
            image: components["schemas"]["MediaAsset"];
            video?: components["schemas"]["MediaAsset"];
            threeD?: components["schemas"]["MediaAsset"];
            html?: components["schemas"]["MediaAsset"];
        };
        MediaAsset: {
            /**
             * Format: uri
             * @example ipfs://QmExample
             */
            url: string;
            /** @example image/png */
            mimeType: string;
            /** @example 1024000 */
            size: number;
            dimensions?: {
                width: number;
                height: number;
            };
        };
        CreateMediaUploadResponse: {
            /** @example abc123 */
            uploadId: string;
            /** @example a1b2c3d4/artwork.png */
            key: string;
            /** @example superrare-ipfs */
            bucket: string;
            /** @example 10000000 */
            partSize: number;
            presignedUrls: string[];
            /** @example https://superrare.myfilebase.com */
            gatewayBaseUrl: string;
        };
        CreateMediaUploadRequest: {
            /** @example 5000000 */
            fileSize: number;
            /** @example artwork.png */
            filename?: string;
        };
        IpfsUploadResponse: {
            /** @example QmExampleCid */
            cid: string;
            /** @example ipfs://QmExampleCid */
            ipfsUrl: string;
            /** @example https://superrare.myfilebase.com/ipfs/QmExampleCid */
            gatewayUrl: string;
        };
        CompleteMediaUploadRequest: {
            /** @example a1b2c3d4/artwork.png */
            key: string;
            /** @example abc123 */
            uploadId: string;
            /** @example superrare-ipfs */
            bucket: string;
            parts: {
                ETag: string;
                PartNumber: number;
            }[];
        };
        GenerateMediaResponse: {
            media: {
                uri: string;
                mimeType: string;
                size?: number;
                dimensions?: string;
            };
        };
        GenerateMediaRequest: {
            /** @example ipfs://QmMediaCid */
            uri: string;
            /** @example image/png */
            mimeType: string;
        };
        Collection: {
            /** @example col_123 */
            collectionId: string;
            /** @example SuperRare Genesis */
            name: string | null;
            /** @example The original SuperRare collection */
            description: string | null;
            /** @example SUPR */
            symbol: string | null;
            /** @example https://example.com/banner.png */
            bannerImage: string | null;
            /** @example https://example.com/preview.png */
            previewImage: string | null;
            owner: components["schemas"]["User"];
            stats: {
                /** @example 1000 */
                tokenCount: number;
                /** @example 250 */
                collectorCount: number;
                /** @example 500 */
                floorPriceUsd: number | null;
                /** @example 10000 */
                topOfferUsd: number | null;
                /** @example 5000000 */
                saleVolumeUsd: number | null;
            };
            /**
             * @example [
             *       "Background",
             *       "Eyes",
             *       "Mouth"
             *     ]
             */
            attributes: string[];
            /**
             * @example [
             *       1
             *     ]
             */
            chainIds: number[];
            /** @example 1704067200 */
            createdAt: number;
        };
        ImportCollectionResponse: {
            imported: boolean;
            collection?: {
                name: string;
                symbol: string;
            };
        };
        ImportCollectionRequest: {
            chainId: components["schemas"]["ChainId"];
            contractAddress: components["schemas"]["EthereumAddress"];
            ownerAddress: components["schemas"]["EthereumAddress"];
        };
        UserProfile: {
            /** @example 0xba5BDe662c17e2aDFF1075610382B9B691296350 */
            address: string;
            /** @example satoshi */
            username: string;
            /** @example Satoshi Nakamoto */
            fullName: string | null;
            stats: {
                /** @example 42 */
                created: number;
                /** @example 15 */
                owned: number;
                /** @example 1000 */
                followerCount: number;
                /** @example true */
                isCollector: boolean;
                /** @example true */
                isCreator: boolean;
            };
        };
        TokenPriceResponse: {
            data: {
                symbol: string;
                priceUsd: number;
                decimals: number;
                chainId: number;
                address: string;
            };
        };
        /**
         * @description Token symbol (case-insensitive)
         * @example rare
         */
        TokenSymbol: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
