import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { Command } from 'commander';
import { commandPath, createRareProgram } from '../src/program.js';

const OUTPUT_PATH = resolve('docs/cli/reference.md');

async function main(): Promise<void> {
  const program = createRareProgram();
  const markdown = renderCliReference(program);

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, markdown);
}

export function renderCliReference(program: Command): string {
  return [
    '---',
    'title: CLI Reference',
    '---',
    '',
    '# CLI Reference',
    '',
    '<!-- This file is generated by `npm run docs:generate`. Do not edit it directly. -->',
    '',
    ...renderCommandTree(program),
  ].join('\n');
}

function renderCommandTree(command: Command): string[] {
  return [
    ...renderCommand(command),
    ...command.commands.flatMap(renderCommandTree),
  ];
}

function renderCommand(command: Command): string[] {
  const path = commandPath(command).join(' ');
  const headingDepth = Math.min(commandPath(command).length + 1, 6);
  const description = command.description();
  const body = [
    `${'#'.repeat(headingDepth)} \`${path}\``,
    '',
    ...(description === '' ? [] : [description, '']),
    '```text',
    command.helpInformation().trimEnd(),
    '```',
    '',
  ];

  return body;
}

await main();
